seed: 1
record_video: yes

environment:
  render: yes
  num_envs: 100
  num_threads: 1
  simulation_dt: 0.0025
  control_dt: 0.01
  max_time: 4.0
  learning_rate: 1e-3
  nminibatches: 10
  noptepochs: 10
  total_timesteps: 10000000
  eval_every_n: 2

  actionScaler: 0.9
  forceRewardCoeff: 5e-3